### ISSUE TITLE
Misleading initial lack of dates in transfer history 

### ISSUE THREAD

**Issue by reverendus** [OasisDEX/oasis#202] opened 2017-02-28 21:28 UTC
Transfer history dates are synced in background, which takes at least a few seconds after we load Oasis. Until that operation gets completed, the "Date" column is completely empty which gives an impression that there is something missing. It would be less misleading if we used throbbers in the date column, exactly as we use them as in the Markets section.

**Comment by pimato** [comment] 2017-04-21 10:16
Closed as an exact duplicate of https://github.com/OasisDEX/oasis/issues/168

**Closed by pimato** 2017-04-21 10:16 UTC
Labels: ui
