### ISSUE TITLE
UI made me falsely believe I lost my wETH tokens; a scary moment

### ISSUE THREAD

**Issue by aylikrek** [OasisDEX/oasis#72] opened 2016-11-11 08:58 UTC
I made a BUY order, which normally got into the order list with a pending state. After a while - before the order went through - the UI quickly showed the text "Error during contract execution" (if a recall the string correctly). The order was the gone from the order lists, but my wETH token amount was still reduced as if the order went through. I was using Metamask. After reloading the page in Chrome, the order was in the lists as if there had not been a problem.

The order transaction in question: 0x786ab82b8b32f3b59bd9becbf9223a6525f16c04afdfb852a614dc60fdafd5e9

**Comment by ramos-j** [comment] 2017-01-11 16:01
Exact same thing happened to me. From the user's perspective, this is _very_ scary, please address it as a non-trivial problem.

**Comment by pimato** [comment] 2017-04-22 17:31
Closed as an exact duplicate of https://github.com/OasisDEX/oasis/issues/72

**Closed by pimato** 2017-04-22 17:31 UTC
