### ISSUE TITLE
Entered order at ask price and it did not fill

### ISSUE THREAD

**Issue by bamos01** [OasisDEX/oasis#59] opened 2016-10-06 01:11 UTC
I entered an order to buy Maker at the same price as the offer but it did not match

**Comment by freekp** [comment] 2016-10-07 13:21
Can you elaborate a little bit?
You created a new order to buy MKR and that should have automatically matched an existing offer or did you click on one of the offers to buy MKR?

**Comment by bamos01** [comment] 2016-10-08 15:55
The former- i created a buy order that should have automatically matched an existing offer.  The order went through successfully such that a bid and an ask at the same price were present on the book.

**Comment by nmushegian** [comment] 2016-10-11 12:23
maker market is not an exchange in the sense that there is no matching engine. As a rule of thumb all operations on chain should be constant time.

**Comment by jorisbontje** [comment] 2016-10-13 07:59
action: Do (or at least suggest) the matching client side.

**Comment by pimato** [comment] 2017-04-22 17:39
Closed as an exact duplicate of https://github.com/OasisDEX/oasis/issues/166

**Closed by pimato** 2017-04-22 17:39 UTC
