### ISSUE TITLE
mkr.market with light client

### ISSUE THREAD

**Issue by jorisbontje** [OasisDEX/oasis#49] opened 2016-09-08 12:12 UTC
> bug report: when I make an order on http://mkr.market, after a minute it says "Contract Execution Failed" and doesn't show the order; however, when I check etherscan everything looks fine, and when I reload the dapp everything looks fine and I see the order

**Comment by jorisbontje** [comment] 2016-09-08 12:12
https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Client-Public-Test

**Comment by pimato** [comment] 2017-04-22 17:43
Closed as an exact duplicate of https://github.com/OasisDEX/oasis/issues/210

**Closed by pimato** 2017-04-22 17:43 UTC
